# Generated by Django 3.2.2 on 2021-05-12 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(verbose_name='username')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date_added')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eblog.post', verbose_name='Post')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
